<?php

use Drupal\user\UserInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\webform\Entity\Webform;
use Drupal\webform\Entity\WebformSubmission;
use Drupal\user\Entity\User;
use Drupal\webform\WebformSubmissionForm;
use Drupal\node\Entity\Node;
use Drupal\Core\Block\BlockBase;
use Drupal\Core\Routing\TrustedRedirectResponse;
use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Core\Render\Markup;
use Drupal\Core\Database\Database;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\Core\Ajax\AjaxResponse;




function assess_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{

  if ($form_id == 'webform_submission_general_question_add_form' || $form_id == 'webform_submission_general_question_security_add_form' || $form_id == 'webform_submission_general_question_analytics_add_form' || $form_id == 'webform_submission_general_question_mobility_add_form' || $form_id == 'webform_submission_general_question_flexibility_add_form') {
    $form['actions']['submit']['#value'] = t('PROCEED');
  }

  if ($form_id == 'webform_submission_productivity_collaborations_add_form') {
    if ($form['progress']['#current_page'] === 'fifth') {
      foreach (array_keys($form['actions']) as $action) {
        if ($action != 'wizard_prev' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {

          $form['actions'][$action]['#submit'][] = 'assess_form_submit';
        }
      }
    }
  } elseif ($form_id == 'webform_submission_mobility_add_form') {
    if ($form['progress']['#current_page'] === 'fifth') {
      foreach (array_keys($form['actions']) as $action) {
        if ($action != 'wizard_prev' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {

          $form['actions'][$action]['#submit'][] = 'assess_mobilty_form_submit';
        }
      }
    }
  } elseif ($form_id == 'webform_submission_security_and_compliance_add_form') {
    if ($form['progress']['#current_page'] === 'fifth') {
      foreach (array_keys($form['actions']) as $action) {
        if ($action != 'wizard_prev' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {

          $form['actions'][$action]['#submit'][] = 'assess_security_and_compliance_form_submit';
        }
      }
    }
  } elseif ($form_id == 'webform_submission_flexibility_efficiency_and_susta_add_form') {
    if ($form['progress']['#current_page'] === 'fifth') {
      foreach (array_keys($form['actions']) as $action) {
        if ($action != 'wizard_prev' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {

          $form['actions'][$action]['#submit'][] = 'assess_flexibility_efficiency_and_compliance_form_submit';
        }
      }
    }
  } elseif ($form_id == 'webform_submission_analytics_and_intelligence_add_form') {
    if ($form['progress']['#current_page'] === 'fifth') {
      foreach (array_keys($form['actions']) as $action) {
        if ($action != 'wizard_prev' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {

          $form['actions'][$action]['#submit'][] = 'assess_analytics_and_intelligence_form_submit';
        }
      }
    }
  } elseif ($form_id == 'webform_submission_report_add_form') {
    // foreach (array_keys($form['actions']) as $action) {
    //   if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {

    // die('hhhh');
    //$form['actions']['action']['#submit'][] = 'download_report_form_submit';
    $form['actions']['submit']['#submit'][] = 'download_report_form_submit';
    //}
    //}
  }
}


function assess_form_submit(array $form, \Drupal\Core\Form\FormStateInterface $form_state)
{
  //die('jjjj');
  $sid = $form_state->getFormObject()->getEntity()->id();
  $a = $form_state->getValue('select_the_statements_that_reflect_your_workplace_and_operations');
  $b = $form_state->getValue('what_percentage_of_your_workforce_when_working_remotely_have_acc');
  $c = $form_state->getValue('are_you_struggling_with_lots_of_manual_and_repetitive_tasks_asso');
  $d = $form_state->getValue('from_0_to_100_do_you_have_a_seamless_work_experience_where_you_c');
  $e = $form_state->getValue('to_what_extend_supports_your_servicedesk_your_customer_s_needs_');

  $aval = (count($a) * 20);
  $bval = (100 - $b);
  $cval = (count($a) * 17);
  $dval = $d;
  $eval = (count($e) * 17);

  $total = ($aval + $bval + $cval + $dval + $eval) / 5;




  $msg = $aval . " " . $bval . " " . $cval . " " . $dval . " " . $eval;

  //submitting the scores and assessment into custom table
  $web_sub_id = $form_state->getFormObject()->getEntity()->id();
  //set current session
  session_start();
  $sessionid = session_id();
  $_SESSION['assess']['sessionid'] = $sessionid;
  //print_r($_SESSION['assess']['sessionid']);die;
  //set current date and time
  date_default_timezone_set('Asia/Kolkata');
  $created = strtotime(date('Y-m-d H:i:s'));

  $conn = Database::getConnection();
  $conn->insert('digital_maturity_score')->fields(
    array(
      'sessionid' => $_SESSION['assess']['sessionid'],
      'websubmissionid' => $web_sub_id,
      'category' => 'productivity-collaborations',
      'score' => $total,
      'created' => $created,
    )
  )->execute();

  $response = new TrustedRedirectResponse('/drupal-8.9.16/results?score=' . $total . '&category=productivity-collaborations' . '&sid=' . $sid);
  $form_state->setResponse($response);
}
function assess_mobilty_form_submit(array $form, \Drupal\Core\Form\FormStateInterface $form_state)
{
  //die('jjjj');
   $sid = $form_state->getFormObject()->getEntity()->id();
    //print_r($sid);die('huh');

  $ma = $form_state->getValue('what_percentage_of_your_workforce_when_working_remotely_have_acc');
  $mb = $form_state->getValue('what_percentage_of_your_workforce_have_seamless_access_to_the_in');
  $mc = $form_state->getValue('when_your_workforce_is_working_remotely_is_their_it_still_manage');
  $md = $form_state->getValue('employees_in_my_company_have_the_ability_to_');
  $me = $form_state->getValue('are_there_certain_departmental_processes_or_systems_that_can_t_b');


  // if ($mc == yes){die('100');
  //   $mmcval = 100;
  // }else {die('99');
  //   $mmcval = 0;
  // };
  $maval = $ma;
  $mbval = $mb;
  $mcval = $mc;
  $mdval = (100 - (count($md) * 17));
  $meval = (100 - (count($me) * 17));

  $total2 = ($maval + $mbval + $mcval + $mdval + $meval) / 5;

  $mmsg = $maval . " " . $mbval . " " . $mcval . " " . $mdval . " " . $meval;

  $web_sub_id = $form_state->getFormObject()->getEntity()->id();
  //set current session
  session_start();
  $sessionid = session_id();
  $_SESSION['assess']['sessionid'] = $sessionid;
  //set current date and time
  date_default_timezone_set('Asia/Kolkata');
  $created = strtotime(date('Y-m-d H:i:s'));

  $conn = Database::getConnection();
  $conn->insert('digital_maturity_score')->fields(
    array(
      'sessionid' => $_SESSION['assess']['sessionid'],
      'websubmissionid' => $web_sub_id,
      'category' => 'mobility',
      'score' => $total2,
      'created' => $created,
    )
  )->execute();

  $response = new TrustedRedirectResponse('/drupal-8.9.16/results?score=' . $total2 . '&category=mobility' .'&sid=' . $sid);
  $form_state->setResponse($response);
}
function assess_security_and_compliance_form_submit(array $form, \Drupal\Core\Form\FormStateInterface $form_state)
{
  $sid = $form_state->getFormObject()->getEntity()->id();;
  //die('jjjj');
  $sa = $form_state->getValue('it_is_the_backbone_of_most_businesses_today_how_resilient_and_se');
  $sb = $form_state->getValue('do_you_have_a_recovery_plan_in_place_that_will_allow_you_to_retu');
  $sc = $form_state->getValue('data_are_one_of_the_most_valuable_assets_of_your_company_on_a_sc');
  $sd = $form_state->getValue('how_are_you_protecting_your_employees_customers_facilities_and_i');
  $se = $form_state->getValue('how_mature_would_you_rate_your_endpoint_and_security_protection_');


  $saval = $sa;
  $sbval = $sb;
  $scval = $sc - 1;
  $sdval = $sd;
  $seval = $se;

  $total3 = ($saval + $sbval + $scval + $sdval + $seval) / 5;

  $smsg = $saval . " " . $sbval . " " . $scval . " " . $sdval . " " . $seval;
  $web_sub_id = $form_state->getFormObject()->getEntity()->id();
  //set current session
  session_start();
  $sessionid = session_id();
  $_SESSION['assess']['sessionid'] = $sessionid;
  //set current date and time
  date_default_timezone_set('Asia/Kolkata');
  $created = strtotime(date('Y-m-d H:i:s'));

  $conn = Database::getConnection();
  $conn->insert('digital_maturity_score')->fields(
    array(
      'sessionid' => $_SESSION['assess']['sessionid'],
      'websubmissionid' => $web_sub_id,
      'category' => 'security_and_compliance',
      'score' => $total3,
      'created' => $created,
    )
  )->execute();
  $response = new TrustedRedirectResponse('/drupal-8.9.16/results?score=' . $total3 . '&category=security_and_compliance' . '&sid=' . $sid);
  $form_state->setResponse($response);
}
function assess_flexibility_efficiency_and_compliance_form_submit(array $form, \Drupal\Core\Form\FormStateInterface $form_state)
{
   $sid = $form_state->getFormObject()->getEntity()->id();
  // die('jjjj');
  $fa = $form_state->getValue('on_a_scale_of_1_lowest_to_5_highest_how_flexible_is_your_it_infr');
  $fb = $form_state->getValue('which_of_the_following_statement_is_true_');
  $fc = $form_state->getValue('from_0_to_100_how_much_do_you_agree_with_this_statement_communic');
  $fd = $form_state->getValue('would_you_like_to_track_all_the_costs_associated_with_scanning_p');
  $fe = $form_state->getValue('which_of_these_activities_are_currently_manual_and_repetitive_ta');

  $faval = (($fa - 1) * 25);
  $fbval = (100 - (count($fb) * 20));
  $fcval = $fc;
  $fdval = $fd;
  $feval = (100 - (count($fe) * 20));

  $total4 = ($faval + $fbval + $fcval + $fdval + $feval) / 5;

  $fmsg = $faval . " " . $fbval . " " . $fcval . " " . $fdval . " " . $feval;



  //print_r($faval);die('jbbbbj');
  $web_sub_id = $form_state->getFormObject()->getEntity()->id();
  //set current session
  session_start();
  $sessionid = session_id();
  $_SESSION['assess']['sessionid'] = $sessionid;
  //set current date and time
  date_default_timezone_set('Asia/Kolkata');
  $created = strtotime(date('Y-m-d H:i:s'));

  $conn = Database::getConnection();
  $conn->insert('digital_maturity_score')->fields(
    array(
      'sessionid' => $_SESSION['assess']['sessionid'],
      'websubmissionid' => $web_sub_id,
      'category' => 'flexibility-efficiency',
      'score' => $total4,
      'created' => $created,
    )
  )->execute();

  $response = new TrustedRedirectResponse('/drupal-8.9.16/results?abc=' . $total4 . '&category=flexibility-efficiency' . '&sid=' . $sid);
  $form_state->setResponse($response);
}
function assess_analytics_and_intelligence_form_submit(array $form, \Drupal\Core\Form\FormStateInterface $form_state)
{
   $sid = $form_state->getFormObject()->getEntity()->id();
  //kint($form_state);die;
  $aa = $form_state->getValue('which_areas_of_your_business_do_you_struggle_with_');
  $ab = $form_state->getValue('do_you_actively_monitor_your_sensitive_data_such_as_personal_or_');
  $ac = $form_state->getValue('do_you_actively_monitor_manage_key_applications_and_their_usage_');
  $ad = $form_state->getValue('do_you_proactively_monitor_manage_your_it_environment_and_any_co');
  $ae = $form_state->getValue('what_precentage_of_your_physical_infrastructure_or_operations_ar');
  // print_r($ac);die;
  $aaval = (100 - (count($aa) * 25));
  $abval = $ab;
  $acval = $ac;
  $adval = $ad;
  $aeval = $ae;

  $total5 = ($aaval + $abval + $acval + $adval + $aeval) / 5;

  $amsg = $aaval . " " . $abval . " " . $acval . " " . $adval . " " . $aeval;

  $web_sub_id = $form_state->getFormObject()->getEntity()->id();
  //set current session
  session_start();
  $sessionid = session_id();
  $_SESSION['assess']['sessionid'] = $sessionid;
  //set current date and time
  date_default_timezone_set('Asia/Kolkata');
  $created = strtotime(date('Y-m-d H:i:s'));

  $conn = Database::getConnection();
  $conn->insert('digital_maturity_score')->fields(
    array(
      'sessionid' => $_SESSION['assess']['sessionid'],
      'websubmissionid' => $web_sub_id,
      'category' => 'analytics-intelligence',
      'score' => $total5,
      'created' => $created,
    )
  )->execute();

  $response = new TrustedRedirectResponse('/drupal-8.9.16/results?score=' . $total5 . '&category=analytics-intelligence' . '&sid=' . $sid);
  $form_state->setResponse($response);
}
function download_report_form_submit(array $form, \Drupal\Core\Form\FormStateInterface $form_state)
{
  // $webform_submission_id = $form_state->getFormObject()->getEntity()->id();
  $values = \Drupal::request()->request->all();
  // $webform_submission = WebformSubmission::load($webform_submission_id);
  // $webform_submission_id = $values->getFormObject()->getEntity()->id();

  $first_name = $values['name'];
  $last_name =  $values['last_name'];
  $email = $values['email'];
  $mobile = $values['telephone_number'];
  // kint($webform_submission_id);
  // die('rohit');
  $test = $first_name . " " . $last_name . " " . $email . " " . $mobile;
  $sid = $form_state->getFormObject()->getEntity()->id();
  //   print "<pre>";
  // print_r($form_state);
  // print "<pre>";
  // die('kkkgggk');

  //$web_sub_id = '67';//$form_state->getFormObject()->getEntity()->id();

  //set current session
  session_start();
  $sessionid = session_id();
  // print_r($sessionid);die;
  $_SESSION['assess']['sessionid'] = $sessionid;
  //set current date and time
  date_default_timezone_set('Asia/Kolkata');
  $created = strtotime(date('Y-m-d H:i:s'));

  $conn = Database::getConnection();
  $conn->insert('digital_maturity_score')->fields(
    array(
      'sessionid' => $_SESSION['assess']['sessionid'],
      // 'websubmissionid2' => $web_sub_id,
      'category' => 'result',
      // 'score' => $total5,
      'firstname' => $first_name,
      'lastname' =>  $last_name,
      'email' => $email,
      // 'mobile' => $created,

    )
  )->execute();
  }





function assess_page_attachments(array &$page)
{
  unset($result1);
  $result1 = [];
  $result1 =  explode("&", $_SERVER['QUERY_STRING']);




  $result2 =  explode("=", $result1[0]);
  $result3 =  explode("=", $result1[1]);
  $result4 =  explode("=", $result1[2]);

  //print($result2[1].' '.$result3[1]);die;
  //$page['url_string'] = $result[1]);
  $page['#attached']['drupalSettings']['myname'] = $result2[1];
  $page['#attached']['drupalSettings']['myname2'] = $result3[1];
  $page['#attached']['drupalSettings']['myname3'] = $result4[1];
}

/**
 * Implements hook_theme() to add the template definition.
 **/
function assess_theme($existing, $type, $theme, $path)
{
  $web_submission_idee = 59;
  return [
    'assess_template' => [
      'variables' => [
        'var1' => $web_submission_idee,
        'var2' => $web_submission_idee,
      ],
      'path' => $path . '/templates',
      'template' => 'assess-template',
    ],
  ];

  return [
    'report_download' => array(
      'template' => 'assessmail-template',  // TWIG File
      'variables' => array('submitted_data' => []),
    ),
  ];
}