<?php
use Drupal\user\UserInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\webform\Entity\Webform;
use Drupal\webform\Entity\WebformSubmission;
use Drupal\user\Entity\User;
use Drupal\webform\WebformSubmissionForm;
use Drupal\node\Entity\Node;
use Drupal\Core\Block\BlockBase;

use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Core\Render\Markup;
use Drupal\Core\Database\Database;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\Core\Ajax\AjaxResponse;

//  * @param $form
//  * @param \Drupal\Core\Form\FormStateInterface $form_state
//  * @param $form_id
 



function dev_new_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
//  if($form_id == 'webform_submission_productivity_collaboration_add_form'){ 
//       $form['actions'][$action]['#submit'][] = 'custom_assessment_form_submit';
//     }
//if ($form['progress']['#current_page'] === 'step_5'){die('kkk');
// foreach (array_keys($form['actions']) as $action) {
//   if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
//     $form['actions'][$action]['#submit'][] = 'custom_assessment_form_submit';
//   }
// }
//   }
//}
   
  //   $form['actions']['submit']['#value'] = t('STARTNOW');
  //  }
  // }
// function assessment_form_submit(array $form, &$form_state)
// {die('jjjj');
//   $webform = \Drupal\webform\Entity\Webform::load('webform_submission_productivity_collaboration_add_form');  //webform id is the webform name
//  if ($webform->hasSubmissions()) {
//    $query = \Drupal::entityQuery('webform_submission')
//      ->condition('webform_id', 'webform_submission_productivity_collaboration_add_form');
//    $result = $query->execute();
//    $submission_data = [];
//    foreach ($result as $item) {
//      $submission = \Drupal\webform\Entity\WebformSubmission::load($item);
//      $submission_data = $submission->getData();
//    }
//   }
//   print "<pre>";
//   print_r($submission_data);
//   print "<pre>";die;
//    }custom_assessment_form_submit

function custom_assessment_form_submit(array $form, \Drupal\Core\Form\FormStateInterface $form_state) {
//die('jjjj');
$a = $form_state->getValue('from_0_to_100_do_you_have_a_seamless_work_experience_where_you_c'); 
$b = $form_state->getValue('what_percentage_of_your_workforce_when_working_remotely_have_acc'); 
$c = $form_state->getValue('when_your_workforce_is_working_remotely_is_their_it_still_manage'); 
$d = $form_state->getValue('how_do_you_manage_document_work_and_other_manual_work_in_your_da'); 
$e = $form_state->getValue('to_what_extend_supports_your_servicedesk_your_customer_s_needs_'); 

 print "<pre>";
   print_r($a);
//   print_r($b);
   //print_r($c);
     print "<pre>";

 die('kkkk');
}